package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * ArteInteresArtista generated by hbm2java
 */
@Entity
@Table(name = "arte_interes_artista", schema = "public")
public class ArteInteresArtista implements java.io.Serializable {

	@NotNull(message="La identificaci�n del ArteInteresArtista no puede ser nula")
	private int idarteinteresartista;
	@NotNull(message="La identificacion_artista del ArteInteresArtista no puede ser nula")
	private Artista artista;
	@NotNull(message="La identificacion_expresionartista del ArteInteresArtista no puede ser nula")
	private ExpresionArtistica expresionArtistica;

	public ArteInteresArtista() {
	}

	public ArteInteresArtista(int idarteinteresartista) {
		this.idarteinteresartista = idarteinteresartista;
	}

	public ArteInteresArtista(int idarteinteresartista, Artista artista, ExpresionArtistica expresionArtistica) {
		this.idarteinteresartista = idarteinteresartista;
		this.artista = artista;
		this.expresionArtistica = expresionArtistica;
	}

	@Id
	@Column(name = "idarteinteresartista", unique = true, nullable = false)
	public int getIdarteinteresartista() {
		return this.idarteinteresartista;
	}

	public void setIdarteinteresartista(int idarteinteresartista) {
		this.idarteinteresartista = idarteinteresartista;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idartista")
	public Artista getArtista() {
		return this.artista;
	}

	public void setArtista(Artista artista) {
		this.artista = artista;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idexpresionartistica")
	public ExpresionArtistica getExpresionArtistica() {
		return this.expresionArtistica;
	}

	public void setExpresionArtistica(ExpresionArtistica expresionArtistica) {
		this.expresionArtistica = expresionArtistica;
	}

}
