package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * ArtistaGrupo generated by hbm2java
 */
@Entity
@Table(name = "artista_grupo", schema = "public")
public class ArtistaGrupo implements java.io.Serializable {
	@NotNull(message="El idartistagrupo es obligatorio")	
	private int idartistagrupo;
	@NotNull(message="El artista es obligatorio")	
	private Artista artista;
	@NotNull(message="El grupo es obligatorio")	
	private Grupo grupo;

	public ArtistaGrupo() {
	}

	public ArtistaGrupo(int idartistagrupo) {
		this.idartistagrupo = idartistagrupo;
	}

	public ArtistaGrupo(int idartistagrupo, Artista artista, Grupo grupo) {
		this.idartistagrupo = idartistagrupo;
		this.artista = artista;
		this.grupo = grupo;
	}

	@Id

	@Column(name = "idartistagrupo", unique = true, nullable = false)
	public int getIdartistagrupo() {
		return this.idartistagrupo;
	}

	public void setIdartistagrupo(int idartistagrupo) {
		this.idartistagrupo = idartistagrupo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idartista")
	public Artista getArtista() {
		return this.artista;
	}

	public void setArtista(Artista artista) {
		this.artista = artista;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idgrupo")
	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

}
