package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Biografia generated by hbm2java
 */
@Entity
@Table(name = "biografia", schema = "public")
public class Biografia implements java.io.Serializable {

	@NotNull(message="El idbiografia es obligatorio")	
	private int idbiografia;
	@NotNull(message="El artista es obligatorio")	
	private Artista artista;
	@NotNull(message="El nombre es obligatorio")
	@Size(min = 1,message="Obligatiro llenar la descripcion")
	private String descripcion;
	@NotNull(message="La fecha es obligatorio")	
	private Date fechacreacion;

	public Biografia() {
	}

	public Biografia(int idbiografia, String descripcion, Date fechacreacion) {
		this.idbiografia = idbiografia;
		this.descripcion = descripcion;
		this.fechacreacion = fechacreacion;
	}

	public Biografia(int idbiografia, Artista artista, String descripcion, Date fechacreacion) {
		this.idbiografia = idbiografia;
		this.artista = artista;
		this.descripcion = descripcion;
		this.fechacreacion = fechacreacion;
	}

	@Id

	@Column(name = "idbiografia", unique = true, nullable = false)
	public int getIdbiografia() {
		return this.idbiografia;
	}

	public void setIdbiografia(int idbiografia) {
		this.idbiografia = idbiografia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idartista")
	public Artista getArtista() {
		return this.artista;
	}

	public void setArtista(Artista artista) {
		this.artista = artista;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechacreacion", nullable = false, length = 22)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

}
