package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * CapaLugar generated by hbm2java
 */
@Entity
@Table(name = "capa_lugar", schema = "public")
public class CapaLugar implements java.io.Serializable {
	@NotNull(message="El idcapalugar es obligatorio")	
	private int idcapalugar;
	@NotNull(message="El idcapa es obligatorio")	
	private Capa capa;
	@NotNull(message="El idlugar es obligatorio")	
	private Lugar lugar;

	public CapaLugar() {
	}

	public CapaLugar(int idcapalugar) {
		this.idcapalugar = idcapalugar;
	}

	public CapaLugar(int idcapalugar, Capa capa, Lugar lugar) {
		this.idcapalugar = idcapalugar;
		this.capa = capa;
		this.lugar = lugar;
	}

	@Id

	@Column(name = "idcapalugar", unique = true, nullable = false)
	public int getIdcapalugar() {
		return this.idcapalugar;
	}

	public void setIdcapalugar(int idcapalugar) {
		this.idcapalugar = idcapalugar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcapa")
	public Capa getCapa() {
		return this.capa;
	}

	public void setCapa(Capa capa) {
		this.capa = capa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idlugar")
	public Lugar getLugar() {
		return this.lugar;
	}

	public void setLugar(Lugar lugar) {
		this.lugar = lugar;
	}

}
