package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Caracteristica generated by hbm2java
 */
@Entity
@Table(name = "caracteristica", schema = "public")
public class Caracteristica implements java.io.Serializable {
	@NotNull(message="El idcaracteristica es obligatorio")	
	private int idcaracteristica;
	@NotNull(message="El nombre es obligatorio")
	@Size(min = 1,max=255,message="255 es el maximo de caracteres")
	private String nombre;
	private Set<CaracteristicaObra> caracteristicaObras = new HashSet<CaracteristicaObra>(0);
	private Set<ExpresionArtisticaCaracteristica> expresionArtisticaCaracteristicas = new HashSet<ExpresionArtisticaCaracteristica>(
			0);
	private Set<ValorCaracteristicaObra> valorCaracteristicaObras = new HashSet<ValorCaracteristicaObra>(0);

	public Caracteristica() {
	}

	public Caracteristica(int idcaracteristica, String nombre) {
		this.idcaracteristica = idcaracteristica;
		this.nombre = nombre;
	}

	public Caracteristica(int idcaracteristica, String nombre, Set<CaracteristicaObra> caracteristicaObras,
			Set<ExpresionArtisticaCaracteristica> expresionArtisticaCaracteristicas,
			Set<ValorCaracteristicaObra> valorCaracteristicaObras) {
		this.idcaracteristica = idcaracteristica;
		this.nombre = nombre;
		this.caracteristicaObras = caracteristicaObras;
		this.expresionArtisticaCaracteristicas = expresionArtisticaCaracteristicas;
		this.valorCaracteristicaObras = valorCaracteristicaObras;
	}

	@Id

	@Column(name = "idcaracteristica", unique = true, nullable = false)
	public int getIdcaracteristica() {
		return this.idcaracteristica;
	}

	public void setIdcaracteristica(int idcaracteristica) {
		this.idcaracteristica = idcaracteristica;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caracteristica")
	public Set<CaracteristicaObra> getCaracteristicaObras() {
		return this.caracteristicaObras;
	}

	public void setCaracteristicaObras(Set<CaracteristicaObra> caracteristicaObras) {
		this.caracteristicaObras = caracteristicaObras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caracteristica")
	public Set<ExpresionArtisticaCaracteristica> getExpresionArtisticaCaracteristicas() {
		return this.expresionArtisticaCaracteristicas;
	}

	public void setExpresionArtisticaCaracteristicas(
			Set<ExpresionArtisticaCaracteristica> expresionArtisticaCaracteristicas) {
		this.expresionArtisticaCaracteristicas = expresionArtisticaCaracteristicas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caracteristica")
	public Set<ValorCaracteristicaObra> getValorCaracteristicaObras() {
		return this.valorCaracteristicaObras;
	}

	public void setValorCaracteristicaObras(Set<ValorCaracteristicaObra> valorCaracteristicaObras) {
		this.valorCaracteristicaObras = valorCaracteristicaObras;
	}

}
