package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
/**
 * CaracteristicaObra generated by hbm2java
 */
@Entity
@Table(name = "caracteristica_obra", schema = "public")
public class CaracteristicaObra implements java.io.Serializable {
	@NotNull(message="El idcaracteristicaobra es obligatorio")	
	private int idcaracteristicaobra;
	@NotNull(message="El idcaracteristica es obligatorio")	
	private Caracteristica caracteristica;
	@NotNull(message="El idobra es obligatorio")	
	private Obra obra;
	@NotNull(message="El idvalorcaracteristicaobra es obligatorio")	
	private ValorCaracteristicaObra valorCaracteristicaObra;
	@NotNull(message="La descripcion es obligatorio")
	@Size(min = 1,message="Obligatorio llenar una descripcion")
	private String decripcion;

	public CaracteristicaObra() {
	}

	public CaracteristicaObra(int idcaracteristicaobra, String decripcion) {
		this.idcaracteristicaobra = idcaracteristicaobra;
		this.decripcion = decripcion;
	}

	public CaracteristicaObra(int idcaracteristicaobra, Caracteristica caracteristica, Obra obra,
			ValorCaracteristicaObra valorCaracteristicaObra, String decripcion) {
		this.idcaracteristicaobra = idcaracteristicaobra;
		this.caracteristica = caracteristica;
		this.obra = obra;
		this.valorCaracteristicaObra = valorCaracteristicaObra;
		this.decripcion = decripcion;
	}

	@Id

	@Column(name = "idcaracteristicaobra", unique = true, nullable = false)
	public int getIdcaracteristicaobra() {
		return this.idcaracteristicaobra;
	}

	public void setIdcaracteristicaobra(int idcaracteristicaobra) {
		this.idcaracteristicaobra = idcaracteristicaobra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcaracteristica")
	public Caracteristica getCaracteristica() {
		return this.caracteristica;
	}

	public void setCaracteristica(Caracteristica caracteristica) {
		this.caracteristica = caracteristica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idobra")
	public Obra getObra() {
		return this.obra;
	}

	public void setObra(Obra obra) {
		this.obra = obra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idvalorcaracteristicaobra")
	public ValorCaracteristicaObra getValorCaracteristicaObra() {
		return this.valorCaracteristicaObra;
	}

	public void setValorCaracteristicaObra(ValorCaracteristicaObra valorCaracteristicaObra) {
		this.valorCaracteristicaObra = valorCaracteristicaObra;
	}

	@Column(name = "decripcion", nullable = false)
	public String getDecripcion() {
		return this.decripcion;
	}

	public void setDecripcion(String decripcion) {
		this.decripcion = decripcion;
	}

}
