package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria", schema = "public")
public class Categoria implements java.io.Serializable {
	@NotNull(message="El idcategoria es obligatorio")	
	private int idcategoria;
	@NotNull(message="El nombre es obligatorio")
	@Size(min = 1,max=100,message="maximo de caracteres 100 y minimo 1 para el nombre")
	private String nombre;
	@NotNull(message="El nombre es obligatorio")
	@Size(min = 1,max=255,message="maximo de caracteres 255 y minimo 1 para la descripcion")
	private String descripcion;
	private Set<CategoriaLugar> categoriaLugars = new HashSet<CategoriaLugar>(0);

	public Categoria() {
	}

	public Categoria(int idcategoria, String nombre, String descripcion) {
		this.idcategoria = idcategoria;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public Categoria(int idcategoria, String nombre, String descripcion, Set<CategoriaLugar> categoriaLugars) {
		this.idcategoria = idcategoria;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.categoriaLugars = categoriaLugars;
	}

	@Id

	@Column(name = "idcategoria", unique = true, nullable = false)
	public int getIdcategoria() {
		return this.idcategoria;
	}

	public void setIdcategoria(int idcategoria) {
		this.idcategoria = idcategoria;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<CategoriaLugar> getCategoriaLugars() {
		return this.categoriaLugars;
	}

	public void setCategoriaLugars(Set<CategoriaLugar> categoriaLugars) {
		this.categoriaLugars = categoriaLugars;
	}

}
