package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Comentario generated by hbm2java
 */
@Entity
@Table(name = "comentario", schema = "public")
public class Comentario implements java.io.Serializable {
	@NotNull(message="El idcomentario es obligatorio")	
	private int idcomentario;
	@NotNull(message="El idruta es obligatorio")	
	private Ruta ruta;
	@NotNull(message="El idusuario es obligatorio")	
	private Usuario usuario;
	@NotNull(message="El desccomentario es obligatorio")
	@Size(min = 1,message="Obligatorio llenar desccomentario")
	private String desccomentario;

	public Comentario() {
	}

	public Comentario(int idcomentario, String desccomentario) {
		this.idcomentario = idcomentario;
		this.desccomentario = desccomentario;
	}

	public Comentario(int idcomentario, Ruta ruta, Usuario usuario, String desccomentario) {
		this.idcomentario = idcomentario;
		this.ruta = ruta;
		this.usuario = usuario;
		this.desccomentario = desccomentario;
	}

	@Id

	@Column(name = "idcomentario", unique = true, nullable = false)
	public int getIdcomentario() {
		return this.idcomentario;
	}

	public void setIdcomentario(int idcomentario) {
		this.idcomentario = idcomentario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idruta")
	public Ruta getRuta() {
		return this.ruta;
	}

	public void setRuta(Ruta ruta) {
		this.ruta = ruta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "desccomentario", nullable = false)
	public String getDesccomentario() {
		return this.desccomentario;
	}

	public void setDesccomentario(String desccomentario) {
		this.desccomentario = desccomentario;
	}

}
