package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "nombreestado"))
public class Estado implements java.io.Serializable {
	@NotNull(message="El idestado es obligatorio")	
	private int idestado;
	@NotNull(message="El nombre es obligatorio")
	@Size(min = 1,max=100,message="Minimo de caracteres es 1 y maximo 100 nombre")
	private String nombreestado;
	@NotNull(message="El descestado es obligatorio")
	@Size(min = 1,max=100,message="Minimo de caracteres es 1 y maximo 100 descestado")
	private String descestado;
	private Set<Ruta> rutas = new HashSet<Ruta>(0);

	public Estado() {
	}

	public Estado(int idestado, String nombreestado, String descestado) {
		this.idestado = idestado;
		this.nombreestado = nombreestado;
		this.descestado = descestado;
	}

	public Estado(int idestado, String nombreestado, String descestado, Set<Ruta> rutas) {
		this.idestado = idestado;
		this.nombreestado = nombreestado;
		this.descestado = descestado;
		this.rutas = rutas;
	}

	@Id

	@Column(name = "idestado", unique = true, nullable = false)
	public int getIdestado() {
		return this.idestado;
	}

	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

	@Column(name = "nombreestado", unique = true, nullable = false, length = 100)
	public String getNombreestado() {
		return this.nombreestado;
	}

	public void setNombreestado(String nombreestado) {
		this.nombreestado = nombreestado;
	}

	@Column(name = "descestado", nullable = false)
	public String getDescestado() {
		return this.descestado;
	}

	public void setDescestado(String descestado) {
		this.descestado = descestado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<Ruta> getRutas() {
		return this.rutas;
	}

	public void setRutas(Set<Ruta> rutas) {
		this.rutas = rutas;
	}

}
