package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * ExpresionArtisticaCaracteristica generated by hbm2java
 */
@Entity
@Table(name = "expresion_artistica_caracteristica", schema = "public")
public class ExpresionArtisticaCaracteristica implements java.io.Serializable {
	@NotNull(message="El idexpresionartisticacaracteristica es obligatorio")	
	private int idexpresionartisticacaracteristica;
	@NotNull(message="El idcaracteristica es obligatorio")	
	private Caracteristica caracteristica;
	@NotNull(message="El idexpresionartistica es obligatorio")	
	private ExpresionArtistica expresionArtistica;

	public ExpresionArtisticaCaracteristica() {
	}

	public ExpresionArtisticaCaracteristica(int idexpresionartisticacaracteristica) {
		this.idexpresionartisticacaracteristica = idexpresionartisticacaracteristica;
	}

	public ExpresionArtisticaCaracteristica(int idexpresionartisticacaracteristica, Caracteristica caracteristica,
			ExpresionArtistica expresionArtistica) {
		this.idexpresionartisticacaracteristica = idexpresionartisticacaracteristica;
		this.caracteristica = caracteristica;
		this.expresionArtistica = expresionArtistica;
	}

	@Id

	@Column(name = "idexpresionartisticacaracteristica", unique = true, nullable = false)
	public int getIdexpresionartisticacaracteristica() {
		return this.idexpresionartisticacaracteristica;
	}

	public void setIdexpresionartisticacaracteristica(int idexpresionartisticacaracteristica) {
		this.idexpresionartisticacaracteristica = idexpresionartisticacaracteristica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcaracteristica")
	public Caracteristica getCaracteristica() {
		return this.caracteristica;
	}

	public void setCaracteristica(Caracteristica caracteristica) {
		this.caracteristica = caracteristica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idexpresionartistica")
	public ExpresionArtistica getExpresionArtistica() {
		return this.expresionArtistica;
	}

	public void setExpresionArtistica(ExpresionArtistica expresionArtistica) {
		this.expresionArtistica = expresionArtistica;
	}

}
