package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * ExpresionArtistica generated by hbm2java
 */
@Entity
@Table(name = "expresion_artistica", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "descripcion"))
public class ExpresionArtistica implements java.io.Serializable {
	@NotNull(message="El idexpresionartistica es obligatorio")	
	private int idexpresionartistica;
	@NotNull(message="El descestado es obligatorio")
	@Size(min = 1,max=60,message="Minimo de caracteres es 1 y maximo 60 descripcion")
	private String descripcion;
	private Set<RutaExpresionArtistica> rutaExpresionArtisticas = new HashSet<RutaExpresionArtistica>(0);
	private Set<ArteInteresArtista> arteInteresArtistas = new HashSet<ArteInteresArtista>(0);
	private Set<Obra> obras = new HashSet<Obra>(0);
	private Set<GrupoExpresionArtistica> grupoExpresionArtisticas = new HashSet<GrupoExpresionArtistica>(0);
	private Set<ExpresionArtisticaCaracteristica> expresionArtisticaCaracteristicas = new HashSet<ExpresionArtisticaCaracteristica>(
			0);
	private Set<ExpresionAutor> expresionAutors = new HashSet<ExpresionAutor>(0);

	public ExpresionArtistica() {
	}

	public ExpresionArtistica(int idexpresionartistica, String descripcion) {
		this.idexpresionartistica = idexpresionartistica;
		this.descripcion = descripcion;
	}

	public ExpresionArtistica(int idexpresionartistica, String descripcion,
			Set<RutaExpresionArtistica> rutaExpresionArtisticas, Set<ArteInteresArtista> arteInteresArtistas,
			Set<Obra> obras, Set<GrupoExpresionArtistica> grupoExpresionArtisticas,
			Set<ExpresionArtisticaCaracteristica> expresionArtisticaCaracteristicas,
			Set<ExpresionAutor> expresionAutors) {
		this.idexpresionartistica = idexpresionartistica;
		this.descripcion = descripcion;
		this.rutaExpresionArtisticas = rutaExpresionArtisticas;
		this.arteInteresArtistas = arteInteresArtistas;
		this.obras = obras;
		this.grupoExpresionArtisticas = grupoExpresionArtisticas;
		this.expresionArtisticaCaracteristicas = expresionArtisticaCaracteristicas;
		this.expresionAutors = expresionAutors;
	}

	@Id

	@Column(name = "idexpresionartistica", unique = true, nullable = false)
	public int getIdexpresionartistica() {
		return this.idexpresionartistica;
	}

	public void setIdexpresionartistica(int idexpresionartistica) {
		this.idexpresionartistica = idexpresionartistica;
	}

	@Column(name = "descripcion", unique = true, nullable = false, length = 60)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expresionArtistica")
	public Set<RutaExpresionArtistica> getRutaExpresionArtisticas() {
		return this.rutaExpresionArtisticas;
	}

	public void setRutaExpresionArtisticas(Set<RutaExpresionArtistica> rutaExpresionArtisticas) {
		this.rutaExpresionArtisticas = rutaExpresionArtisticas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expresionArtistica")
	public Set<ArteInteresArtista> getArteInteresArtistas() {
		return this.arteInteresArtistas;
	}

	public void setArteInteresArtistas(Set<ArteInteresArtista> arteInteresArtistas) {
		this.arteInteresArtistas = arteInteresArtistas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expresionArtistica")
	public Set<Obra> getObras() {
		return this.obras;
	}

	public void setObras(Set<Obra> obras) {
		this.obras = obras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expresionArtistica")
	public Set<GrupoExpresionArtistica> getGrupoExpresionArtisticas() {
		return this.grupoExpresionArtisticas;
	}

	public void setGrupoExpresionArtisticas(Set<GrupoExpresionArtistica> grupoExpresionArtisticas) {
		this.grupoExpresionArtisticas = grupoExpresionArtisticas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expresionArtistica")
	public Set<ExpresionArtisticaCaracteristica> getExpresionArtisticaCaracteristicas() {
		return this.expresionArtisticaCaracteristicas;
	}

	public void setExpresionArtisticaCaracteristicas(
			Set<ExpresionArtisticaCaracteristica> expresionArtisticaCaracteristicas) {
		this.expresionArtisticaCaracteristicas = expresionArtisticaCaracteristicas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expresionArtistica")
	public Set<ExpresionAutor> getExpresionAutors() {
		return this.expresionAutors;
	}

	public void setExpresionAutors(Set<ExpresionAutor> expresionAutors) {
		this.expresionAutors = expresionAutors;
	}

}
