package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Grupo generated by hbm2java
 */
@Entity
@Table(name = "grupo", schema = "public")
public class Grupo implements java.io.Serializable {
	@NotNull(message="El idgrupo es obligatorio")	
	private int idgrupo;
	@NotNull(message="El nombregrupo es obligatorio")
	@Size(min = 1,max=80,message="Minimo de caracteres es 1 y maximo 80 nombre")
	private String nombregrupo;
	@NotNull(message="La descripcion es obligatorio")
	@Size(min = 1,message="Minimo de caracteres es 1 descripcion")
	private String descripcion;
	private Set<GrupoExpresionArtistica> grupoExpresionArtisticas = new HashSet<GrupoExpresionArtistica>(0);
	private Set<ArtistaGrupo> artistaGrupos = new HashSet<ArtistaGrupo>(0);

	public Grupo() {
	}

	public Grupo(int idgrupo, String nombregrupo, String descripcion) {
		this.idgrupo = idgrupo;
		this.nombregrupo = nombregrupo;
		this.descripcion = descripcion;
	}

	public Grupo(int idgrupo, String nombregrupo, String descripcion,
			Set<GrupoExpresionArtistica> grupoExpresionArtisticas, Set<ArtistaGrupo> artistaGrupos) {
		this.idgrupo = idgrupo;
		this.nombregrupo = nombregrupo;
		this.descripcion = descripcion;
		this.grupoExpresionArtisticas = grupoExpresionArtisticas;
		this.artistaGrupos = artistaGrupos;
	}

	@Id

	@Column(name = "idgrupo", unique = true, nullable = false)
	public int getIdgrupo() {
		return this.idgrupo;
	}

	public void setIdgrupo(int idgrupo) {
		this.idgrupo = idgrupo;
	}

	@Column(name = "nombregrupo", nullable = false, length = 80)
	public String getNombregrupo() {
		return this.nombregrupo;
	}

	public void setNombregrupo(String nombregrupo) {
		this.nombregrupo = nombregrupo;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupo")
	public Set<GrupoExpresionArtistica> getGrupoExpresionArtisticas() {
		return this.grupoExpresionArtisticas;
	}

	public void setGrupoExpresionArtisticas(Set<GrupoExpresionArtistica> grupoExpresionArtisticas) {
		this.grupoExpresionArtisticas = grupoExpresionArtisticas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupo")
	public Set<ArtistaGrupo> getArtistaGrupos() {
		return this.artistaGrupos;
	}

	public void setArtistaGrupos(Set<ArtistaGrupo> artistaGrupos) {
		this.artistaGrupos = artistaGrupos;
	}

}
