package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Obra generated by hbm2java
 */
@Entity
@Table(name = "obra", schema = "public")
public class Obra implements java.io.Serializable {
	@NotNull(message="El idobra es obligatorio")	
	private int idobra;
	@NotNull(message="El idexpresionartistica es obligatorio")	
	private ExpresionArtistica expresionArtistica;
	@NotNull(message="El descestado es obligatorio")
	@Size(min = 1,max=255,message="Minimo de caracteres es 1 y maximo 255 nombre")
	private String nombre;
	@NotNull(message="La longitud es obligatoria")	
	private double longitud;
	@NotNull(message="La latitud es obligatoria")	
	private double latitud;
	@NotNull(message="La direccion es obligatoria")
	@Size(min = 1,max=255,message="Minimo de caracteres es 1 y maximo 255 direccion")
	private String direccion;
	@NotNull(message="El autor es obligatorio")
	@Size(min = 1,max=100,message="Minimo de caracteres es 1 y maximo 100 autor")
	private String autor;
	@NotNull(message="La fecha es obligatorio")	
	private Date fechacreacion;
	
	private int visitas;
	private Set<OpinionUsuario> opinionUsuarios = new HashSet<OpinionUsuario>(0);
	private Set<Portafolio> portafolios = new HashSet<Portafolio>(0);
	private Set<ReferenciaObraUsuario> referenciaObraUsuarios = new HashSet<ReferenciaObraUsuario>(0);
	private Set<Soporte> soportes = new HashSet<Soporte>(0);
	private Set<CaracteristicaObra> caracteristicaObras = new HashSet<CaracteristicaObra>(0);
	private Set<RutaObra> rutaObras = new HashSet<RutaObra>(0);

	public Obra() {
	}

	public Obra(int idobra, String nombre, double longitud, double latitud, String direccion, String autor,
			Date fechacreacion, int visitas) {
		this.idobra = idobra;
		this.nombre = nombre;
		this.longitud = longitud;
		this.latitud = latitud;
		this.direccion = direccion;
		this.autor = autor;
		this.fechacreacion = fechacreacion;
		this.visitas = visitas;
	}

	public Obra(int idobra, ExpresionArtistica expresionArtistica, String nombre, double longitud, double latitud,
			String direccion, String autor, Date fechacreacion, int visitas, Set<OpinionUsuario> opinionUsuarios,
			Set<Portafolio> portafolios, Set<ReferenciaObraUsuario> referenciaObraUsuarios, Set<Soporte> soportes,
			Set<CaracteristicaObra> caracteristicaObras, Set<RutaObra> rutaObras) {
		this.idobra = idobra;
		this.expresionArtistica = expresionArtistica;
		this.nombre = nombre;
		this.longitud = longitud;
		this.latitud = latitud;
		this.direccion = direccion;
		this.autor = autor;
		this.fechacreacion = fechacreacion;
		this.visitas = visitas;
		this.opinionUsuarios = opinionUsuarios;
		this.portafolios = portafolios;
		this.referenciaObraUsuarios = referenciaObraUsuarios;
		this.soportes = soportes;
		this.caracteristicaObras = caracteristicaObras;
		this.rutaObras = rutaObras;
	}

	@Id

	@Column(name = "idobra", unique = true, nullable = false)
	public int getIdobra() {
		return this.idobra;
	}

	public void setIdobra(int idobra) {
		this.idobra = idobra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idexpresionartistica")
	public ExpresionArtistica getExpresionArtistica() {
		return this.expresionArtistica;
	}

	public void setExpresionArtistica(ExpresionArtistica expresionArtistica) {
		this.expresionArtistica = expresionArtistica;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "longitud", nullable = false, precision = 17, scale = 17)
	public double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(double longitud) {
		this.longitud = longitud;
	}

	@Column(name = "latitud", nullable = false, precision = 17, scale = 17)
	public double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(double latitud) {
		this.latitud = latitud;
	}

	@Column(name = "direccion", nullable = false)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "autor", nullable = false, length = 80)
	public String getAutor() {
		return this.autor;
	}

	public void setAutor(String autor) {
		this.autor = autor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechacreacion", nullable = false, length = 22)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	@Column(name = "visitas", nullable = false)
	public int getVisitas() {
		return this.visitas;
	}

	public void setVisitas(int visitas) {
		this.visitas = visitas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "obra")
	public Set<OpinionUsuario> getOpinionUsuarios() {
		return this.opinionUsuarios;
	}

	public void setOpinionUsuarios(Set<OpinionUsuario> opinionUsuarios) {
		this.opinionUsuarios = opinionUsuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "obra")
	public Set<Portafolio> getPortafolios() {
		return this.portafolios;
	}

	public void setPortafolios(Set<Portafolio> portafolios) {
		this.portafolios = portafolios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "obra")
	public Set<ReferenciaObraUsuario> getReferenciaObraUsuarios() {
		return this.referenciaObraUsuarios;
	}

	public void setReferenciaObraUsuarios(Set<ReferenciaObraUsuario> referenciaObraUsuarios) {
		this.referenciaObraUsuarios = referenciaObraUsuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "obra")
	public Set<Soporte> getSoportes() {
		return this.soportes;
	}

	public void setSoportes(Set<Soporte> soportes) {
		this.soportes = soportes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "obra")
	public Set<CaracteristicaObra> getCaracteristicaObras() {
		return this.caracteristicaObras;
	}

	public void setCaracteristicaObras(Set<CaracteristicaObra> caracteristicaObras) {
		this.caracteristicaObras = caracteristicaObras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "obra")
	public Set<RutaObra> getRutaObras() {
		return this.rutaObras;
	}

	public void setRutaObras(Set<RutaObra> rutaObras) {
		this.rutaObras = rutaObras;
	}

}
