package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name = "pais", schema = "public")
public class Pais implements java.io.Serializable {
	@NotNull(message="El idpais es obligatorio")	
	private int idpais;
	@NotNull(message="El nombre del pais es obligatorio")	
	@Size(min = 1,max=255,message="Minimo de caracteres es 1 y maximo 255 nombre del pais")
	private String nombre;
	@NotNull(message="La abreviaci�n es obligatorio")	
	@Size(min = 1,max=5,message="Minimo de caracteres es 1 y maximo 5 abreviaci�n")
	private String abreviatura;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Pais() {
	}

	public Pais(int idpais, String nombre, String abreviatura) {
		this.idpais = idpais;
		this.nombre = nombre;
		this.abreviatura = abreviatura;
	}

	public Pais(int idpais, String nombre, String abreviatura, Set<Usuario> usuarios) {
		this.idpais = idpais;
		this.nombre = nombre;
		this.abreviatura = abreviatura;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "idpais", unique = true, nullable = false)
	public int getIdpais() {
		return this.idpais;
	}

	public void setIdpais(int idpais) {
		this.idpais = idpais;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abreviatura", nullable = false, length = 5)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
