package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * Portafolio generated by hbm2java
 */
@Entity
@Table(name = "portafolio", schema = "public")
public class Portafolio implements java.io.Serializable {
	@NotNull(message="El idportafolio es obligatorio")		
	private int idportafolio;
	@NotNull(message="El idartista es obligatorio")		
	private Artista artista;
	@NotNull(message="El idobra es obligatorio")		
	private Obra obra;

	public Portafolio() {
	}

	public Portafolio(int idportafolio) {
		this.idportafolio = idportafolio;
	}

	public Portafolio(int idportafolio, Artista artista, Obra obra) {
		this.idportafolio = idportafolio;
		this.artista = artista;
		this.obra = obra;
	}

	@Id

	@Column(name = "idportafolio", unique = true, nullable = false)
	public int getIdportafolio() {
		return this.idportafolio;
	}

	public void setIdportafolio(int idportafolio) {
		this.idportafolio = idportafolio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idartista")
	public Artista getArtista() {
		return this.artista;
	}

	public void setArtista(Artista artista) {
		this.artista = artista;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idobra")
	public Obra getObra() {
		return this.obra;
	}

	public void setObra(Obra obra) {
		this.obra = obra;
	}

}
