package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "descripcion"))
public class Rol implements java.io.Serializable {
	@NotNull(message="El idrol es obligatorio")		
	private int idrol;
	@NotNull(message="El idopinionusuario es obligatorio")	
	@Size(min = 1,max=50,message="Minimo de caracteres es 1 y maximo 50 descripcion")
	private String descripcion;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Rol() {
	}

	public Rol(int idrol, String descripcion) {
		this.idrol = idrol;
		this.descripcion = descripcion;
	}

	public Rol(int idrol, String descripcion, Set<Usuario> usuarios) {
		this.idrol = idrol;
		this.descripcion = descripcion;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "idrol", unique = true, nullable = false)
	public int getIdrol() {
		return this.idrol;
	}

	public void setIdrol(int idrol) {
		this.idrol = idrol;
	}

	@Column(name = "descripcion", unique = true, nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
