package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * RutaObra generated by hbm2java
 */
@Entity
@Table(name = "ruta_obra", schema = "public")
public class RutaObra implements java.io.Serializable {
	@NotNull(message="El idrutaobra es obligatorio")		
	private int idrutaobra;
	@NotNull(message="El idobra es obligatorio")		
	private Obra obra;
	@NotNull(message="El idruta es obligatorio")		
	private Ruta ruta;

	public RutaObra() {
	}

	public RutaObra(int idrutaobra) {
		this.idrutaobra = idrutaobra;
	}

	public RutaObra(int idrutaobra, Obra obra, Ruta ruta) {
		this.idrutaobra = idrutaobra;
		this.obra = obra;
		this.ruta = ruta;
	}

	@Id

	@Column(name = "idrutaobra", unique = true, nullable = false)
	public int getIdrutaobra() {
		return this.idrutaobra;
	}

	public void setIdrutaobra(int idrutaobra) {
		this.idrutaobra = idrutaobra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idobra")
	public Obra getObra() {
		return this.obra;
	}

	public void setObra(Obra obra) {
		this.obra = obra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idruta")
	public Ruta getRuta() {
		return this.ruta;
	}

	public void setRuta(Ruta ruta) {
		this.ruta = ruta;
	}

}
