package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * SoporteLugar generated by hbm2java
 */
@Entity
@Table(name = "soporte_lugar", schema = "public")
public class SoporteLugar implements java.io.Serializable {
	@NotNull(message="El idsoportelugar es obligatorio")		
	private int idsoportelugar;
	@NotNull(message="El idlugar es obligatorio")		
	private Lugar lugar;
	@NotNull(message="El idtiposoporte es obligatorio")		
	private TipoSoporte tipoSoporte;
	@NotNull(message="El idopinionusuario es obligatorio")	
	@Size(min = 1,max=255,message="Minimo de caracteres es 1 y maximo 255 para la descripci�n")
	private String descripcion;

	public SoporteLugar() {
	}

	public SoporteLugar(int idsoportelugar, String descripcion) {
		this.idsoportelugar = idsoportelugar;
		this.descripcion = descripcion;
	}

	public SoporteLugar(int idsoportelugar, Lugar lugar, TipoSoporte tipoSoporte, String descripcion) {
		this.idsoportelugar = idsoportelugar;
		this.lugar = lugar;
		this.tipoSoporte = tipoSoporte;
		this.descripcion = descripcion;
	}

	@Id

	@Column(name = "idsoportelugar", unique = true, nullable = false)
	public int getIdsoportelugar() {
		return this.idsoportelugar;
	}

	public void setIdsoportelugar(int idsoportelugar) {
		this.idsoportelugar = idsoportelugar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idlugar")
	public Lugar getLugar() {
		return this.lugar;
	}

	public void setLugar(Lugar lugar) {
		this.lugar = lugar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtiposoporte")
	public TipoSoporte getTipoSoporte() {
		return this.tipoSoporte;
	}

	public void setTipoSoporte(TipoSoporte tipoSoporte) {
		this.tipoSoporte = tipoSoporte;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
