package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * TipoSoporte generated by hbm2java
 */
@Entity
@Table(name = "tipo_soporte", schema = "public")
public class TipoSoporte implements java.io.Serializable {
	@NotNull(message="El idtiposoporte es obligatorio")		
	private int idtiposoporte;
	@NotNull(message="La descripcion es obligatorio")	
	@Size(min = 1,max=60,message="Minimo de caracteres es 1 y maximo 60 para descripcion")
	private String descripcion;
	private Set<Soporte> soportes = new HashSet<Soporte>(0);
	private Set<SoporteLugar> soporteLugars = new HashSet<SoporteLugar>(0);

	public TipoSoporte() {
	}

	public TipoSoporte(int idtiposoporte, String descripcion) {
		this.idtiposoporte = idtiposoporte;
		this.descripcion = descripcion;
	}

	public TipoSoporte(int idtiposoporte, String descripcion, Set<Soporte> soportes, Set<SoporteLugar> soporteLugars) {
		this.idtiposoporte = idtiposoporte;
		this.descripcion = descripcion;
		this.soportes = soportes;
		this.soporteLugars = soporteLugars;
	}

	@Id

	@Column(name = "idtiposoporte", unique = true, nullable = false)
	public int getIdtiposoporte() {
		return this.idtiposoporte;
	}

	public void setIdtiposoporte(int idtiposoporte) {
		this.idtiposoporte = idtiposoporte;
	}

	@Column(name = "descripcion", nullable = false, length = 60)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoSoporte")
	public Set<Soporte> getSoportes() {
		return this.soportes;
	}

	public void setSoportes(Set<Soporte> soportes) {
		this.soportes = soportes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoSoporte")
	public Set<SoporteLugar> getSoporteLugars() {
		return this.soporteLugars;
	}

	public void setSoporteLugars(Set<SoporteLugar> soporteLugars) {
		this.soporteLugars = soporteLugars;
	}

}
