package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * TipoLugarLugar generated by hbm2java
 */
@Entity
@Table(name = "tipo_lugar_lugar", schema = "public")
public class TipoLugarLugar implements java.io.Serializable {
	@NotNull(message="El idtipolugarlugar es obligatorio")		
	private int idtipolugarlugar;
	@NotNull(message="El idlugar es obligatorio")		
	private Lugar lugar;
	@NotNull(message="El tipolugar es obligatorio")		
	private TipoLugar tipoLugar;

	public TipoLugarLugar() {
	}

	public TipoLugarLugar(int idtipolugarlugar) {
		this.idtipolugarlugar = idtipolugarlugar;
	}

	public TipoLugarLugar(int idtipolugarlugar, Lugar lugar, TipoLugar tipoLugar) {
		this.idtipolugarlugar = idtipolugarlugar;
		this.lugar = lugar;
		this.tipoLugar = tipoLugar;
	}

	@Id

	@Column(name = "idtipolugarlugar", unique = true, nullable = false)
	public int getIdtipolugarlugar() {
		return this.idtipolugarlugar;
	}

	public void setIdtipolugarlugar(int idtipolugarlugar) {
		this.idtipolugarlugar = idtipolugarlugar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idlugar")
	public Lugar getLugar() {
		return this.lugar;
	}

	public void setLugar(Lugar lugar) {
		this.lugar = lugar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipolugar")
	public TipoLugar getTipoLugar() {
		return this.tipoLugar;
	}

	public void setTipoLugar(TipoLugar tipoLugar) {
		this.tipoLugar = tipoLugar;
	}

}
