package com.amapearte.modelo;
// Generated 5/08/2017 04:28:14 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * ValorCaracteristicaObra generated by hbm2java
 */
@Entity
@Table(name = "valor_caracteristica_obra", schema = "public")
public class ValorCaracteristicaObra implements java.io.Serializable {
	
	@NotNull(message="El idvalorcaracteristicaobra es obligatorio")	
	private int idvalorcaracteristicaobra;	
	@NotNull(message="La caracteristica es obligatorio")	
	private Caracteristica caracteristica;
	@NotNull(message="La descripcion caracteristica es obligatorio")
	@Size(min = 1, max = 255,message="El numero de caracteres maximo para la descripcion caracteristica debe ser de 255")
	private String descripcioncaracteristica;
	private Set<CaracteristicaObra> caracteristicaObras = new HashSet<CaracteristicaObra>(0);

	public ValorCaracteristicaObra() {
	}

	public ValorCaracteristicaObra(int idvalorcaracteristicaobra, String descripcioncaracteristica) {
		this.idvalorcaracteristicaobra = idvalorcaracteristicaobra;
		this.descripcioncaracteristica = descripcioncaracteristica;
	}

	public ValorCaracteristicaObra(int idvalorcaracteristicaobra, Caracteristica caracteristica,
			String descripcioncaracteristica, Set<CaracteristicaObra> caracteristicaObras) {
		this.idvalorcaracteristicaobra = idvalorcaracteristicaobra;
		this.caracteristica = caracteristica;
		this.descripcioncaracteristica = descripcioncaracteristica;
		this.caracteristicaObras = caracteristicaObras;
	}

	@Id

	@Column(name = "idvalorcaracteristicaobra", unique = true, nullable = false)
	public int getIdvalorcaracteristicaobra() {
		return this.idvalorcaracteristicaobra;
	}

	public void setIdvalorcaracteristicaobra(int idvalorcaracteristicaobra) {
		this.idvalorcaracteristicaobra = idvalorcaracteristicaobra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcaracteristica")
	public Caracteristica getCaracteristica() {
		return this.caracteristica;
	}

	public void setCaracteristica(Caracteristica caracteristica) {
		this.caracteristica = caracteristica;
	}

	@Column(name = "descripcioncaracteristica", nullable = false)
	public String getDescripcioncaracteristica() {
		return this.descripcioncaracteristica;
	}

	public void setDescripcioncaracteristica(String descripcioncaracteristica) {
		this.descripcioncaracteristica = descripcioncaracteristica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "valorCaracteristicaObra")
	public Set<CaracteristicaObra> getCaracteristicaObras() {
		return this.caracteristicaObras;
	}

	public void setCaracteristicaObras(Set<CaracteristicaObra> caracteristicaObras) {
		this.caracteristicaObras = caracteristicaObras;
	}

}
